### ISSUE TITLE
mkfs.fat ignores user-set reserved sectors count that is less than cluster size

### ISSUE THREAD

**Issue by nachanon** [dosfstools/dosfstools#44] opened 2017-04-11 07:57 UTC
While I was experimenting with partition data alignment in digital camera's SD card, I ran into an issue when I invoked `mkfs.fat` with:

* Manually-specified cluster size (`-s`), and...
* Manually-specified reserved sector count (`-R`) that is _less than the size of cluster_.

I found that in this condition, `mkfs.fat` **ignored my reserved sector count specification**, and used the same value as cluster size.

In my understanding, the varying reserved-area size is done for improving physical alignment; but this behavior _has to be documented_ (see note about manual page at the end of this post). And when user explicitly specify it, user's value **should take precedence**; or else `-R` option would became useless for dealing with any nontrivial alignment issues (e.g. Win9x's FDISK-partitioned hard disk with 4 KiB sector).

Exact steps to reproduce:

* Make an empty image file with the size of 15941632 sectors: `dd if=/dev/zero of=test.img bs=512 count=15941632`
* Run `mkfs.fat` on the image file in verbose mode, with cluster size of 64 sectors, and reserved area size of 32 sectors: `mkfs.fat -v -s 64 -R 32 test.img`
* You would see that `mkfs.fat` gave following output:

		mkfs.fat 4.1 (2017-01-24)
		Auto-selecting FAT32 for large filesystem
		test.img has 255 heads and 63 sectors per track,
		hidden sectors 0x0000;
		logical sector size is 512,
		using 0xf8 media descriptor, with 15941632 sectors;
		drive number 0x80;
		filesystem has 2 32-bit FATs and 64 sectors per cluster.
		FAT size is 1984 sectors, and provides 249025 clusters.
		There are 64 reserved sectors.
		Volume ID is 393de7df, no volume label.
	
	From the output, you would see that `mkfs.fat` **used 64-sector reserved area, despite being explicitly instructed to use 32 sectors** via `-R` option.
	
* If one inspected the image with [GNU mtools](https://www.gnu.org/software/mtools/)' `minfo`, they would see following report:
	
		device information:
		===================
		filename="/tmp/test.img"
		sectors per track: 63
		heads: 255
		cylinders: 993
		
		mformat command line: mformat -T 15941632 -h 255 -s 63 -H 0 c:
		
		bootsector information
		======================
		banner:"mkfs.fat"
		sector size: 512 bytes
		cluster size: 64 sectors
		reserved (boot) sectors: 64
		fats: 2
		max available root directory slots: 0
		small size: 0 sectors
		media descriptor byte: 0xf8
		sectors per fat: 0
		sectors per track: 63
		heads: 255
		hidden sectors: 0
		big size: 15941632 sectors
		physical drive id: 0x80
		reserved=0x0
		dos4=0x29
		serial number: 393DE7DF
		disk label="NO NAME    "
		disk type="FAT32   "
		Big fatlen=1984
		Extended flags=0x0000
		FS version=0x0000
		rootCluster=2
		infoSector location=1
		backup boot sector=6
		
		Infosector:
		signature=0x41615252
		free clusters=249024
		last allocated cluster=2
	
	The report confirms that reserved area is 64 sectors-long, instead of the desired 32-sector.

Notes:

* This problem also apply to situations when cluster size is automatically determined.
* This problem also affects older releases, like dosfstools 3.0.13.
* **This varying reserved-area size behavior [disagrees with manual page](https://github.com/dosfstools/dosfstools/blob/v4.1/manpages/mkfs.fat.8.in#L130)**: which said it defaulted to 32 without any mention of its dependency on cluster size.
* Unrelated: `mkfs.vfat` doesn't seem to allow reserved sectors count that is not a multiple of cluster size. (Specifying one will result in a rounding up to the next larger multiple).

dosfstools: 4.1 (source)
mtools: 4.0.17-1 (debian)
System: Debian GNU/Linux 7.0 Wheezy i386

**Comment by pali** [comment] 2018-08-19 15:05
Duplicate of https://github.com/dosfstools/dosfstools/issues/67

**Closed** 2019-02-10 01:11 UTC
