### ISSUE TITLE
-l option with a file of zero size

### ISSUE THREAD

**Issue by changosan** [dosfstools/dosfstools#186] opened 2022-12-27 05:50 UTC
Hi. I'm trying to write a script that runs mkfs.fat with the -l option after running badblocks, but I get an error message.
```shell
$ sudo badblocks -wv -b 2048 -t 0xff -t 0x00 -o sda1.badblocks /dev/sda1
$ sudo mkfs.vfat -l sda1.badblocks -F 32 -n boot1 -s 4 -v /dev/sda1
mkfs.fat 4.2 (2021-01-31)
...
getline: No such file or directory
mkfs.fat: Error while reading bad blocks file
$ echo $?
1
$ ls -l sda1.badblocks
-rw-r--r-- 1 user  user  0 Dec 27 13:59 sda1.badblocks
```
PC environment
* OS : Raspberry Pi OS Bullseye
* sda1 : USB-SSD 120GB
```shell
$ uname -a
Linux user 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux
```
I'm not familiar with `getline` function. But I tried inserting a '\n' in the file and the error disappeared.
```shell
$ ls -l sda1.badblocks
-rw-r--r-- 1 user  user  1 Dec 27 14:00 sda1.badblocks
$ od -c sda1.badblocks
0000000  \n
0000001
$ sudo mkfs.fat -l sda1.badblocks -F 32 -n boot1 -s 4 -v /dev/sda1
$ echo $?
0
```
I tried mkfs.ext4 as well, but no error occurred, by the way.
```shell
$ sudo badblocks -wv -b 4096 -t 0xff -t 0x00 -o sda2.badblocks /dev/sda2
$ sudo mkfs.ext4 -b 4096 -l sda2.badblocks -L root1 -v /dev/sda2
$ ls -l sda2.badblocks
-rw-r--r-- 1 root root 0 Dec 11 11:16 sda2.badblocks
```
So, I came up with the following script.
```shell
$ cat chkblock.sh
#!/bin/sh

FILE="sda1.badblocks"
if [ -s "$FILE" ]; then
  sudo mkfs.vfat -l "$FILE" -F 32 -n boot1 -s 4 -v /dev/sda1
else
  sudo mkfs.vfat -F 32 -n boot1 -s 4 -v /dev/sda1
fi
```
Is this a good solution? Any suggestions would be appreciated.

**Comment by pali** [comment] 2022-12-27 10:13
And you want to achieve?

**Comment by changosan** [comment] 2022-12-28 00:35
I wanted to achieve.
I thought the -c option was calling badblocks, but that's not the case.
I'm starting to think that the -c option might be a good option, so I'll give it some thought.
Thanks.

**Comment by pali** [comment] 2022-12-28 00:38
Could you please describe a little bit more that is the issue and what you want to do that does not work?

**Comment by changosan** [comment] 2022-12-30 03:15
## **I want to do**
I want to create a script that runs mkfs.fat with the -l option after reading and writing tests with badblocks.
## **issue**
When there are no errors in badblocks, that is, when the output file size is zero, executing mkfs.fat using the -l option stops halfway.
## **What I did**
Inserted `printf` into mkfs.fat.c of dosfstools-4.2.
```shell
$ cat mkfs.fat.c
static void get_list_blocks(char *filename)
	ssize_t length = getline(&line, &linesize, listfile);
	printf("length=%zd, errno=%d\n", length, errno);      ##### insert this line
	if (length < 0) {
	    if (errno == 0) /* end of file */
```
### **test**
```shell
$ sudo dd if=/dev/zero of=/dev/sda1
dd: writing to '/dev/sda1': No space left on device
524289+0 records in
524288+0 records out
268435456 bytes (268 MB, 256 MiB) copied, 35.322 s, 7.6 MB/s
$ ls -l sda1.badblocks
-rw-r--r-- 1 rp001 rp001 0 Dec 28 19:24 sda1.badblocks   ##### size zero
$ od -c sda1.badblocks
0000000         ##### No newline code
$ sudo ./mkfs.fat -l sda1.badblocks -F 32 -n boot1 -s 4 /dev/sda1
mkfs.fat 4.2 (2021-01-31)
mkfs.fat: Warning: lowercase labels might not work properly on some systems
length=-1, errno=2     #####
getline: No such file or directory
mkfs.fat: Error while reading bad blocks file
$ echo $?
1     #####
```
Due to length=-1, errno=2, the mkfs.fat is stopped at exit(1).
errno2: No such file or directory?
## **request**
I think it would be nice to work with -l option even when babblocks output file size is zero, or the usage is clarified.

Since I am going on a trip, I will reply on January 9th.

**Comment by pali** [comment] 2022-12-30 12:06
Ok, thank you. Now I see what you mean.

I was not able to reproduce this issue. With empty file I'm always getting `errno=0`. So seems that this is system specific.

Anyway, I read POSIX documentation of `getline()` function and it says:
> If no characters were read, and the end-of-file indicator for the stream is set, or if the stream is at end-of-file, the end-of-file indicator for the stream shall be set and the function shall return -1. If an error occurs, the error indicator for the stream shall be set, and the function shall return -1 and set errno to indicate the error.
> The ferror() or feof() functions should be used to distinguish between an error condition and an end-of-file condition.

It does not say anything that errno must be set to zero when end-of-file occurs. So it looks like an issue in dosfstools code, but interesting is that on all tested systems it is set to zero.

Could you try following patch if it fixes this issue for you?

```diff
diff --git a/src/mkfs.fat.c b/src/mkfs.fat.c
index 02ae4391689a..417b07a55630 100644
--- a/src/mkfs.fat.c
+++ b/src/mkfs.fat.c
@@ -474,7 +474,7 @@ static void get_list_blocks(char *filename)
 	lineno++;
 	ssize_t length = getline(&line, &linesize, listfile);
 	if (length < 0) {
-	    if (errno == 0) /* end of file */
+	    if (feof(listfile))
 		break;
 
 	    pdie("Error while reading bad blocks file");
```

**Comment by changosan** [comment] 2023-01-09 10:02
I tried the patch you suggested and it works fine.
```c
$ cat -n mkfs.fat.c
   450          ssize_t length = getline(&line, &linesize, listfile);
   451          printf("length=%zd, errno=%d\n", length, errno);     #####
   452          if (length < 0) {
   453              //if (errno == 0) /* end of file */
   454              if (feof(listfile))     #####
   455                  break;
```
```shell
$ sudo ./mkfs.fat -l sda1.badblocks -F 32 -n boot1 -s 4 /dev/sda1
mkfs.fat 4.2 (2021-01-31)
mkfs.fat: Warning: lowercase labels might not work properly on some systems
length=-1, errno=0

$ echo $?
0
```

And I Figured out where the errno=2 is occurring. They are openat(,"slaves",); and openat(,"removable",); in the get_sector_size function in device_info.c.
```c
$ cat -n device_info.c
   229	    printf("before slaves: errno=%d\n", errno);     #####
   230	    fd = openat(blockfd, "slaves", O_RDONLY | O_DIRECTORY);
   231	    printf("after slaves: fd=%d, errno=%d\n", fd, errno);     #####
   232	    if (fd >= 0) {

   245	    }else {     #####
   246	        if (errno != 0)     #####
   247	            errno = 0;     #####
   248	    }

   265	        printf("before_removable: errno=%d\n", errno);     #####
   266	        fd = openat(blockfd, "removable", O_RDONLY);
   267	        printf("after_removable: fd=%d, errno=%d\n", fd, errno);     #####
   268	        if (fd >= 0) {

   277	        }else {     #####
   278	            if (errno != 0)     #####
   279	                errno = 0;     #####
   280	        }
```
```c
$ cat -n mkfs.fat.c
   450          ssize_t length = getline(&line, &linesize, listfile);
   451          printf("length=%zd, errno=%d\n", length, errno);     #####
   452          if (length < 0) {
   453              if (errno == 0) /* end of file */
   454              //if (feof(listfile))
   455                  break;
```
```shell
$ sudo ./mkfs.fat -l sda1.badblocks -F 32 -n boot1 -s 4 /dev/sda1
mkfs.fat 4.2 (2021-01-31)
before slaves: errno=0
after slaves: fd=-1, errno=2
before_removable: errno=0
after_removable: fd=-1, errno=2
mkfs.fat: Warning: lowercase labels might not work properly on some systems
length=-1, errno=0

$ echo $?
0
```
Sorry if it's hard to read because I haven't mastered how to use git yet.
What are the "slaves" and the "removable"? Don't they exist on my system?
My system hardware: Raspberry Pi 3B+ or 4B, SD-Card, Powered USB hub, USB-SSD, input & output tools

In addition, I found getline(getdelim) and openat in gnulib, so I'm looking closely at them now.
https://git.savannah.gnu.org/gitweb/?p=gnulib.git -> stable-tree -> lib
There are several patterns for getline to return -1. Should I download gnulib and compile and test it?
My system software:
```shell
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110

$ sudo apt list | grep gnulib
gnulib/stable,stable 20210102~ebaa53c-1 all
```

In any case, I think that it is desirable to fix the error handling at getline and openat.
What do you think of Pali?

**Comment by changosan** [comment] 2023-01-09 10:15
Sorry, the first test result with the addition of "if (feof(listfile))" is modified below.
length=-1, errno=2.

**Comment by pali** [comment] 2023-01-09 18:39
> I tried the patch you suggested and it works fine.

Perfect!

> What are the "slaves" and the "removable"?

Directory slaves contains slave devices of the current one. For example something like subpartitions... File removable contains 0 if device is fixed and 1 if removable (e.g. USB flash disk).

> Don't they exist on my system?

They should. I looked at this issue and I figure out that you found another bug and I can reproduce it. Both entities for partitioned devices are in the parent. This patch could fix it:

```diff
diff --git a/src/device_info.c b/src/device_info.c
index ded980e519f0..e45e674f564d 100644
--- a/src/device_info.c
+++ b/src/device_info.c
@@ -385,6 +385,8 @@ static void get_block_linux_info(struct device_info *info, int devfd, dev_t rdev
 
     /* Check if device is slave of another device and therefore is virtual */
     fd = openat(blockfd, "slaves", O_RDONLY | O_DIRECTORY);
+    if (fd < 0 && errno == ENOENT && info->partition != 0)
+        fd = openat(blockfd, "../slaves", O_RDONLY | O_DIRECTORY);
     if (fd >= 0) {
         dir = fdopendir(fd);
         if (dir) {
@@ -416,6 +418,8 @@ static void get_block_linux_info(struct device_info *info, int devfd, dev_t rdev
     if (info->type == TYPE_UNKNOWN) {
         removable = 0;
         fd = openat(blockfd, "removable", O_RDONLY);
+        if (fd < 0 && errno == ENOENT && info->partition != 0)
+            fd = openat(blockfd, "../removable", O_RDONLY);
         if (fd >= 0) {
             file = fdopen(fd, "r");
             if (file) {
```

> There are several patterns for getline to return -1. Should I download gnulib and compile and test it?

I think you do not need it. Normally C/POSIX functions do _not_ update errno value when function success. And EOF state is not error. So it makes sense that getline did not touch errno in this case. And previous errno from openat() was propagated at the wrong place. As mentioned in the previous post, correct way should be to check feof() and not errno for EOF.

**Comment by changosan** [comment] 2023-01-10 02:51
I tried the patch above.
```c
$ cat -n device_info.c
   229	    printf("before slaves: errno=%d\n", errno);
   230	    fd = openat(blockfd, "slaves", O_RDONLY | O_DIRECTORY);
   231	    if (fd < 0 && errno == ENOENT && info->partition != 0)     #####
   232	        fd = openat(blockfd, "../slaves", O_RDONLY | O_DIRECTORY);     #####
   233	    printf("after slaves: fd=%d, errno=%d\n", fd, errno);
   234	    if (fd >= 0) {

   267	        printf("before_removable: errno=%d\n", errno);
   268	        fd = openat(blockfd, "removable", O_RDONLY);
   269	        if (fd < 0 && errno == ENOENT && info->partition != 0)     #####
   270	            fd = openat(blockfd, "../removable", O_RDONLY);     #####
   271	        printf("after_removable: fd=%d, errno=%d\n", fd, errno);
   272	        if (fd >= 0) {
```
```shell
$ sudo ./mkfs.fat -l sda1.badblocks -F 32 -n boot1 -s 4 /dev/sda1
mkfs.fat 4.2 (2021-01-31)
before slaves: errno=0
after slaves: fd=5, errno=2
before_removable: errno=2
after_removable: fd=5, errno=2
mkfs.fat: Warning: lowercase labels might not work properly on some systems
length=-1, errno=2
$ echo $?
0
```
Both slaves and removable are now fd=5. It looks good, but is this okay?

**Comment by pali** [comment] 2023-01-13 23:20
Both issues are now fixed in the git master branch.

**Closed** 2023-01-13 23:19 UTC
