### ISSUE TITLE
FAT12 support

### ISSUE THREAD

**Issue by mikebdp2** [dosfstools/dosfstools#138] opened 2020-04-03 17:11 UTC
It's sad to see there are no good opensource Linux tools to work with a FAT12 filesystem, it's being unfairly ignored. We shouldn't need Windows to work with the floppies and floppy images.

Please add FAT12 support to your library.

**Comment by pali** [comment] 2020-04-03 17:13
dosfstools supports FAT12

**Comment by mikebdp2** [comment] 2020-04-03 17:22
@pali I need to resize a FAT12 floppy image, and it seems dosfstools does not support that

**Comment by pali** [comment] 2020-04-03 17:48
Resizing is not supported by dosfstools, see related issue: https://github.com/dosfstools/dosfstools/issues/91

**Comment by pali** [comment] 2020-04-04 20:57
Duplicate of #91

**Closed by pali** 2020-04-04 20:57 UTC
