### ISSUE TITLE
malloc : Cannot allocate memory

### ISSUE THREAD

**Issue by shuhanzhang97** [dosfstools/dosfstools#204] opened 2023-06-14 09:59 UTC
Hi, 
I'm using fsck.fat to fix a FAT32 file system, but it shows that kernel can not allocate more memory to fsck.
The embedded system that I used only has 30MB memory. So I think the memory allocations in read first FAT, second FAT and struct cluster_owner exceed the maximum memory on my embedded system. Is there any ways to reduce the alloc size in fsck.fat tool?

**Comment by pali** [comment] 2023-06-14 10:22
duplicate of #140

**Closed by pali** 2023-06-14 10:22 UTC

**Comment by shuhanzhang97** [comment] 2023-06-15 02:41
The patches you mentioned in #56 are no longer present. Could you please update the new link for these patches?
