### ISSUE TITLE
Add progress bar or percencentage to cluster scanning

### ISSUE THREAD

**Issue by jgomer2001** [dosfstools/dosfstools#148] opened 2020-12-03 21:09 UTC
Recently I used fsck to check a 64GB stick (using verbose flag). "Checking for bad clusters" was shown in the console for longer than forever :) so I would be nice to show a percentage of progress to get some feedback.

An excerpt of output is as follows:

> fsck.fat 4.1 (2017-01-24)
> ...
>    1951419 data clusters (63944097792 bytes)
> ...
> Checking file ...
> Checking for bad clusters.

**Comment by pali** [comment] 2020-12-19 13:18
Duplicate of #58

**Closed by pali** 2020-12-19 13:18 UTC
