### ISSUE TITLE
New official release before Debian 11 freeze

### ISSUE THREAD

**Issue by Neustradamus** [dosfstools/dosfstools#152] opened 2021-01-08 07:40 UTC
Hello the Team, @andreasbombe,

I wish you a Happy New Year!

It is possible to create a real new build at this time?
The goal is to have the version before the Debian 11 freeze (2021-01-12).
- https://tracker.debian.org/pkg/dosfstools

The last official version is very old, 4 years soon:
- dosfstools 4.1 has been released this on 24 Jan 2017
- https://github.com/dosfstools/dosfstools/releases

The changes since this 4.1: https://github.com/dosfstools/dosfstools/compare/v4.1...master

The next Debian will be in 2023.

Thanks in advance.

**Comment by Neustradamus** [comment] 2021-01-10 08:39
@andreasbombe: Are you ready to release it before Debian 11 freeze?

**Comment by pali** [comment] 2021-01-30 11:57
Duplicate of #120

**Closed by pali** 2021-01-30 11:57 UTC

**Comment by pabs3** [comment] 2021-02-05 01:07
@andreasbombe said on IRC that he will upload it before the freeze.
